// <auto-generated />
using Blazor_LeadManagement_HDIP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_LeadManagement_HDIP.Server.Migrations
{
    [DbContext(typeof(Data.AppContext))]
    [Migration("20220806152927_LeadTasks")]
    partial class LeadTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blazor_LeadManagement_HDIP.Shared.Lead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MyLeads");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyName = "IBM",
                            CustomerEmail = "j.sheehan@ibm.com",
                            CustomerNumber = "0979282743",
                            FirstName = "John",
                            LastName = "Sheehan",
                            LeadDescription = "Attended Event: Blal blah"
                        },
                        new
                        {
                            ID = 2,
                            CompanyName = "Amazon",
                            CustomerEmail = "j.b@aws.com",
                            CustomerNumber = "097343433",
                            FirstName = "Jeff",
                            LastName = "Bezos",
                            LeadDescription = "Attended Event: AWS"
                        },
                        new
                        {
                            ID = 3,
                            CompanyName = "Tesla",
                            CustomerEmail = "elon.m@teslamotors.com",
                            CustomerNumber = "09792832323",
                            FirstName = "Elon",
                            LastName = "Musk",
                            LeadDescription = "Attended Event: AI and Ethics"
                        },
                        new
                        {
                            ID = 4,
                            CompanyName = "HSE",
                            CustomerEmail = "j.sheehan@hse.ie",
                            CustomerNumber = "0979282222",
                            FirstName = "Jenny",
                            LastName = "Sheehan",
                            LeadDescription = "Attended Event: Engineering for the future"
                        });
                });

            modelBuilder.Entity("Blazor_LeadManagement_HDIP.Shared.LeadTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("MyLeadTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Email Sent asking for a call time",
                            LeadId = 1,
                            Name = "Email Sent",
                            TaskType = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Not interested in our product, just attended event",
                            LeadId = 1,
                            Name = "Call",
                            TaskType = "Call"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Connection sent to stay in contact",
                            LeadId = 1,
                            Name = "LinkedIn Connection Sent",
                            TaskType = "LinkedIn"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Email Sent asking for a demo time",
                            LeadId = 2,
                            Name = "Email Sent",
                            TaskType = "Email"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Email Sent asking what piqued their interest going to the event",
                            LeadId = 3,
                            Name = "Email Sent",
                            TaskType = "Email"
                        });
                });

            modelBuilder.Entity("Blazor_LeadManagement_HDIP.Shared.LeadTask", b =>
                {
                    b.HasOne("Blazor_LeadManagement_HDIP.Shared.Lead", "Lead")
                        .WithMany("Tasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Blazor_LeadManagement_HDIP.Shared.Lead", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
